sdp.js
test/sdp.js

both from the spec values as well as Plan B

add support for parsing msid

---

sdp.js
test/sdp.js

parses RTCRtcpParameters as described in
http://draft.ortc.org/#rtcrtcpparameters*

parse RTCRtcpParameters

---

test/sdp.js

see https://github.com/webrtc/adapter/pull/465

dtls: lowercase algorithm

---

sdp.js
test/sdp.js

sdp: parse a=ice-options

---

sdp.js
test/sdp.js

so far this was іgnored by chance. Also adds tests.

extmap: handle direction attribute

---

sdp.js
test/sdp.js

parseCandidate: parse optional attributes

---

sdp.js
test/sdp.js

makes the candidate a numeric property

ice candidate: component is numeric

---

package.json
test/.eslintrc
test/sdp.js

and use a bit es6 in the tests

test: rewrite tests in mocha/sino/chai

---

test/sdp.js

increases coverage to
77.39% Statements 219/283 63.49% Branches 80/126 81.82% Functions 45/55 77.39% Lines 219/283

test: even more coverage

---

test/sdp.js

increases coverage to 80%
80.92% Statements 229/283 66.67% Branches 84/126 87.27% Functions 48/55 80.92% Lines 229/283

test: add parseMsid coverage

---

test/sdp.js

bringing coverage up to almost 90%

more coverage

---

.travis.yml
package.json

adds codecov.io for coverage reports.

coverage: add codecov

---

test/sdp.js

more a test for the CI service really...

test: add test for boilerplate

---

sdp.js
test/sdp.js

also writes the session version.
@armouroflight I mostly made it so i can do a proper "session id remains constant but sess-ver increases" test ;-)

writeBoilerPlate: write session version

---

sdp.js
test/sdp.js

adds a helper function which parses the mline

add parseMLine helper

---

test/sdp.js

test: improve coverage

---

sdp.js
test/sdp.js

as described in https://tools.ietf.org/html/rfc4566#section-5.2
Also style-changes to parseMLine.

add support for parsing o= lines

---

sdp.js
test/sdp.js

mostly for testing. Not very efficient right now.

add getDescription and getMediaSection helpers

---

sdp.js
test/sdp.js

like telephone-event which has
a=fmtp:100 0-15

improve handling of non-key-value fmtp parameters

---

sdp.js
test/sdp.js

got renamed in https://github.com/w3c/ortc/issues/738

add 'channels' to rtpmap parsing/serialization

---

.npmignore
test/sdp.js

add npmignore

---

sdp.js
test/sdp.js

using a very naive implementation.

add isValidSDP helper

---

sdp.js
test/sdp.js

ice candidates: add address as an alias to ip

---

sdp.js
test/sdp.js

fixes #62
Note that it does not support parsing the keyParams and keeps them a string.

add support for parsing + write SDES a=crypto

---

sdp.js
test/sdp.js

which is defined as the remainder, split by ' '

fix a=crypto sessionParams

---

sdp.js
test/sdp.js

see #64 for sessionParams
see #62 for parsing keyParams
pondering whether I should split them and publish the latter as new version but...

fixes sessionParams serialization and adds keyParameters parser/writer

---

sdp.js
test/sdp.js

getIceParameters: dont throw on SDP without ice-ufrag and ice-pwd

---

sdp.js
test/sdp.js

see #26 -- non breaking change, this is just forward-compatible

writeCandidate: translate component rtp=>1/rtcp=>2

---

sdp.js

fix typo: boilder->boiler

---

package.json
sdp.d.ts

Updated for v3 changes, but have been using these with stanza for ages.

Add TypeScript definitions

---

sdp.d.ts
sdp.js
test/sdp.js

https://datatracker.ietf.org/doc/html/rfc8285#section-5

parse and serialize extmap attributes
